apiVersion: v1
kind: Service
metadata:
  name: image-understanding-service
spec:
  selector:
    app: image-understanding-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5010
  type: NodePort
