apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-understanding-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: image-understanding-app
  template:
    metadata:
      labels:
        app: image-understanding-app
    spec:
      containers:
      - name: image-understanding-container
        image: saeedkasmani/image-understanding-app:latest
        ports:
        - containerPort: 5010



